<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Admin\Programa;

class ProgramaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "357", "programa" => "BECAS COMECYT-EDOMEX. CIENCIA EDOMEX"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "358", "programa" => "FAMILIAS FUERTES CON APOYOS AGRICOLAS. FOMENTO A LA AGRICULTURA ORGANICA"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "359", "programa" => "SANIDAD Y CERTIFICACION AGROPECUARIA. ACCIONES PRIORITARIAS FITOSANITARIAS"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "360", "programa" => "EDOMEX MAS PRODUCTIVO. CAPACITACION ESPECIALIZADA Y ASISTENCIA TECNICA PARA PERSONAS PRODUCTORAS"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "336", "programa" => "INFRAESTRUCTURA. EQUIPAMIENTO, MAQUINARIA Y MATERIAL BIOLÓGICO (SUBSECTOR PESCA Y ACUÍCOLA) "]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "337", "programa" => "INFRAESTRUCTURA. EQUIPAMIENTO, MAQUINARIA Y MATERIAL BIOLÓGICO (SUBSECTOR PECUARIO) "]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "338", "programa" => "INFRAESTRUCTURA. EQUIPAMIENTO, MAQUINARIA Y MATERIAL BIOLÓGICO (SUBSECTOR AGRÍCOLA) "]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "339", "programa" => "PAQUETES TECNOLÓGICOS AGRICOLAS, PECUARIOS, DE PESCA Y ACUÍCOLAS (SUBSECTOR AGRÍCOLA)"]);
      $programa = Programa::create (["cve_dependencia" => "212000000","id" => "340", "programa" => "ESTUDIOS TÉCNICOS FORESTALES"]);
      $programa = Programa::create (["cve_dependencia" => "212000000","id" => "344", "programa" => "CERTIFICACION INTERNACIONAL FSC"]);
      $programa = Programa::create (["cve_dependencia" => "228000000","id" => "343", "programa" => "BECA ELISA CARRILLO CABRERA"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "341", "programa" => "FOMENTO, VINCULACION Y PROMOCIÓN A LA COMERCIALIZACION"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "342", "programa" => "CONSTRUCCIÓN  Y/O REHABILITACIÓN DE OBRA HIDROAGRÍCOLA"]);
      $programa = Programa::create (["cve_dependencia" => "204000000","id" => "346", "programa" => "APOYO AL DESEMPLEO"]);
      $programa = Programa::create (["cve_dependencia" => "214000000","id" => "221", "programa" => "BECAS PARA HIJOS DE PERIODISTAS"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "222", "programa" => "EL VALOR DE PERMANECER ESTUDIANDO"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "223", "programa" => "JÓVENES EN MOVIMIENTO EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "224000000","id" => "224", "programa" => "FAMILIAS FUERTES VIVIENDA INDÍGENA DIGNA"]);
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "355", "programa" => "ESTANCIAS DE INVESTIGACION ESPECIALIZADAS COMECYT EDOMEX"]);
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "356", "programa" => "CATEDRAS COMECYT EDOMEX"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "279", "programa" => "\"FAMILIAS FUERTES CON BECAS ROSAS\" BECAS PARA HIJAS E HIJOS DE MADRE O TUTORA DESAPARECIDA, VÍCTIMA DE FEMINICIDIO U HOMICIDIO DOLOSO"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "280", "programa" => "\"FAMILIAS FUERTES CON BECAS POR DISCAPACIDAD O ENFERMEDADES\" BECAS PARA ALUMNOS CON VIH, DIABETES O CÁNCER"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "281", "programa" => "BECAS PROYECTA ESTADO DE MÉXICO"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "282", "programa" => "BECA TALENTO EDOMÉX  "]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "283", "programa" => "BECA EDOMÉX OLIMPIADA DEL CONOCIMIENTO"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "284", "programa" => "BECAS EDOMÉX ESPERANZA AZTECA"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "285", "programa" => "BECAS EDOMÉX PARA HIJOS DE MIGRANTES"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "286", "programa" => "BECA EDOMÉX MAMÁ JOVEN"]);
      $programa = Programa::create (["cve_dependencia" => "224000000","id" => "347", "programa" => "FAMILIAS FUERTES VIVIENDA RURAL"]);
      $programa = Programa::create (["cve_dependencia" => "224000000","id" => "348", "programa" => "PISO FIRME INDIGENA"]);
      $programa = Programa::create (["cve_dependencia" => "214000000","id" => "220", "programa" => "BECAS PARA PERIODISTAS"]);
      $programa = Programa::create (["cve_dependencia" => "224000000","id" => "226", "programa" => "FAMILIAS FUERTES CON VIVIENDA ECOLÓGICA"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "227", "programa" => "PROYECTOS PRODUCTIVOS EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "228", "programa" => "BRINDAR CURSOS DE CAPACITACIÓN EN MATERIA COMERCIAL"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "229", "programa" => "REHABILITAR ÁREAS DE CARGA Y DESCARGA, VENTA, PATIOS DE MANIOBRAS, TECHUMBRE, INSTALACIONES ELÉCTRICAS Y CAMBIO DE FACHADA DEL MERCADO DE LA FLOR \"XOCHIQUETZAL\" DE TENANCINGO"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "230", "programa" => "REHABILITACIÓN DE 9 MERCADOS CON TRABAJOS DE CAMBIO DE PISO, TECHUMBRE, ESTRUCTURAS, SANITARIOS, PINTURA INTERIOR Y EXTERIOR"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "231", "programa" => "REHABILITAR Y DOTAR DE EQUIPO AL RASTRO MUNICIPAL DE ACULCO"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "232", "programa" => "REHABILITACIÓN DE TECHUMBRE, FACHADAS, PISOS, PINTURA INTERIOR Y EXTERIOR DEL MERCADO 1RO. DE SEPTIEMBRE DE IXTLAHUACA"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "233", "programa" => "SUBSIDIO DE MEMBRESÍA GS1 MÉXICO 2018"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "234", "programa" => "SUBSIDIO PARA EL REGISTRO DE MARCA 2018"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "235", "programa" => "APOYO EN LA COMERCIALIZACIÓN DE PRODUCTOS ARTESANALES DE SAN FELIPE DEL PROGRESO COMPROMISO DE GOBIERNO"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "236", "programa" => "APOYO EN LA COMERCIALIZACIÓN DE PRODUCTOS ARTESANALES DE SAN PEDRO TULTEPEC, LERMA COMPROMISO DE GOBIERNO"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "237", "programa" => "ATENCIÓN A LA INDUSTRIA"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "238", "programa" => "ATRACCIÓN A INVERSIÓN NACIONAL"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "239", "programa" => "PARTICIPACIÓN EN FERIAS Y EVENTOS NACIONALES"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "240", "programa" => "ATENCIÓN A INVERSIONISTAS POTENCIALES"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "241", "programa" => "DESARROLLO DE PROYECTOS DE EXPORTACIÓN"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "242", "programa" => "ASESORÍAS TÉCNICAS EN COMERCIO EXTERIOR"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "243", "programa" => "CAPACITACIÓN DE COMERCIO EXTERIOR"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "244", "programa" => "MISIONES Y FERIAS INTERNACIONALES"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "245", "programa" => "OFRECER ASESORÍA ESPECIALIZADA A INVERSIONISTAS"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "246", "programa" => "GESTIÓN DE TRÁMITES EMPRESARIALES CONTENIDOS EN LA LEY DE COMPETITIVIDAD, ORDENAMIENTO COMERCIAL Y ANTE LA COMISIÓN ESTATAL DE ATENCIÓN EMPRESARIAL"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "247", "programa" => "BRINDAR ASESORAMIENTO GEOLÓGICO-MINERA"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "248", "programa" => "ELABORACIÓN DE ESTUDIOS GEOLÓGICOS, MINEROS Y AMBIENTALES"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "249", "programa" => "CURSOS DE CAPACITACIÓN GEOLÓGICA Y MINERA"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "250", "programa" => "BRINDAR ASESORÍA GEOLÓGICO AMBIENTAL A LA CIUDADANÍA"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "251", "programa" => "FORTALECIENDO TU EMPRESA EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "345", "programa" => "CANASTA ALIMENTARIA"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "252", "programa" => "IMPULSO EMPRENDEDOR EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "253", "programa" => "CAPACITACIÓN MIPYME EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "254", "programa" => "CONSULTORÍA MIPYMES EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "255", "programa" => "FAMILIAS FUERTES EVALUACIÓN DE PROYECTOS"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "256", "programa" => "MIPYMES EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "257", "programa" => "ASESORÍA EDOMÉX A EMPRESAS MEXIQUENSES"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "349", "programa" => "ASISTENCIA TECNICA Y CAPACITACION"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "181", "programa" => "programa DE DESARROLLO SOCIAL FOMENTO A LA REPRODUCCIÓN FRUTÍCOLA"]);
      $programa = Programa::create (["cve_dependencia" => "204000000","id" => "166", "programa" => "FERIAS DE EMPLEO"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "169", "programa" => "programa DE DESARROLLO SOCIAL ADULTOS EN GRANDE"]);
      $programa = Programa::create (["cve_dependencia" => "204000000","id" => "193", "programa" => "PORTAL DEL EMPLEO"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "167", "programa" => "programa DE DESARROLLO SOCIAL MUJERES QUE TRABAJAN EN GRANDE POR SU COMUNIDAD"]);
      $programa = Programa::create (["cve_dependencia" => "225000000","id" => "182", "programa" => "EDOMÉX MÁS TURÍSTICO"]);
      $programa = Programa::create (["cve_dependencia" => "225000000","id" => "183", "programa" => "PROGRAMAS DE FORTALECIMIENTO AL CORREDOR TURÍSTICO TEOTIHUACÁN (MEJORAMIENTO DE FACHADAS)"]);
      $programa = Programa::create (["cve_dependencia" => "225000000","id" => "184", "programa" => "programa DE DESARROLLO TURÍSTICO EN MUNICIPIOS DE LA \"RUTA DE SOR JUANA\" (MEJORAMIENTO DE FACHADAS)"]);
      $programa = Programa::create (["cve_dependencia" => "225000000","id" => "185", "programa" => "HECHO EN EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "225000000","id" => "186", "programa" => "PUEBLOS MÁGICOS"]);
      $programa = Programa::create (["cve_dependencia" => "225000000","id" => "187", "programa" => "DESARROLLO TURÍSTICO DE SANTUARIOS DE LA MARIPOSA MONARCA"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "174", "programa" => "FAMILIAS FUERTES CON BECAS DE INCLUSIÓN (BECAS PARA ESTUDIANTES INDÍGENAS)"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "194", "programa" => "CÁNCER CERVICO ÚTERINO"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "195", "programa" => "CÁNCER DE MAMA"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "196", "programa" => "CENTRO DE ATENCIÓN A DIABÉTICOS"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "197", "programa" => "VIH"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "198", "programa" => "TUBERCULOSIS"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "199", "programa" => "QUEMADOS"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "200", "programa" => "IMAGENOLOGÍA"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "201", "programa" => "CONSULTA DE UNIDADES CONVOY"]);
      $programa = Programa::create (["cve_dependencia" => "204000000","id" => "68", "programa" => "FOMENTO AL AUTOEMPLEO"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "4", "programa" => "BECA SUPERIOR EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "137", "programa" => "BECAS EN EL EXTRANJERO PARA ESTUDIANTES SOBRESALIENTES"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "24", "programa" => "COMPROMISO SEGURIDAD ALIMENTARIA VERTIENTE  ZAP (COINCIDES)"]);
      $programa = Programa::create (["cve_dependencia" => "223000000","id" => "94", "programa" => "CONDUCE SEGURO EDOMÉX. LICENCIA DE SERVICIO PARTICULAR"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1035", "programa" => "PROG PARA EL DESARROLLO DE LA INDUSTRIA DEL SOFTWARE (PROSOFT)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1015", "programa" => "PROG DE COORDINACION PARA EL APOYO A LA PRODUCCION INDIGENA (PROCAPI)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1090", "programa" => "PROG DE DESARROLLO PARCELARIO"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "7", "programa" => "COMPROMISO SEGURIDAD ALIMENTARIA DEL ESTADO DE MEXICO VERTIENTE FAO (ZONA NORORIENTE)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1084", "programa" => "PROG DE AGUA LIMPIA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1005", "programa" => "FORTALECIMIENTO A LA TRANSVERSALIDAD DE LA PERSPECTIVA DE GENERO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1109", "programa" => "PROG DE APOYO A LAS INSTANCIAS DE MUJERES EN LAS ENTIDADES FEDERATIVAS, PARA IMPLEMENTAR Y EJECUTAR PROG DE PREVENCION DE LA VIOLENCIA CONTRA LAS MUJERES"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "154", "programa" => "TABLETS A ESTUDIANTES INDÍGENAS"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "89", "programa" => "FAMILIAS FUERTES CON FOMENTO ACUÍCOLA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1008", "programa" => "PROG ALBERGUES ESCOLARES INDIGENAS (PAEI)"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "106", "programa" => "CREDENCIAL ADULTOS MAYORES EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "10", "programa" => "FONDO MIXTO DE INVERSIÓN RURAL EN EL ESTADO DE MÉXICO (FOMIMEX) (FONDO DE INDEMNIZACIÓN A PRODUCTORES RURALES MEXIQUENSES)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1023", "programa" => "PROG DE ATENCION A CONTINGENCIAS CLIMATOLOGICAS"]);
      $programa = Programa::create (["cve_dependencia" => "204000000","id" => "67", "programa" => "EDOMÉX: ASESORÍA PARA EL TRABAJO"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "82", "programa" => "programa DE CONCURRENCIA CON ENTIDADES FEDERATIVAS (PROYECTOS PRODUCTIVOS O ESTRATÉGICAS DESARROLLO RURAL)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1019", "programa" => "APOYOS PARA EL FOMENTO FINANCIERO Y TECNOLOGICO DE LOS SECTORES AGROPECUARIO Y PESQUERO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1041", "programa" => "PROG NACIONAL DE BECAS Y FINANCIAMIENTO (PRONABES)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "138", "programa" => "ESTÍMULO PARA ALUMNOS CON DISCAPACIDAD MOTRIZ O MÚLTIPLE"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "91", "programa" => "PREMIO A TU GRAN ESFUERZO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1098", "programa" => "programa HABITAT"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "155", "programa" => "MATERIAL DIDÁCTICO PARA USAER"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1042", "programa" => "PROG ESCUELAS DE CALIDAD"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "77", "programa" => "DESARROLLO DE LA INFRAESTRUCTURA AGROPECUARIA FAMILIAS FUERTES (MAQUINARIA PARA LA CONSTRUCCIÓN DE INFRAESTRUCTURA AGROPECUARIA: CAMINOS DE SACACOSECHA Y OBRAS DE SUBSUELO Y TERRACEO)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "11", "programa" => "programa ESCUELA SEGURA"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "76", "programa" => "DESARROLLO DE LA INFRAESTRUCTURA AGROPECUARIA FAMILIAS FUERTES (MAQUINARIA PARA LA CONSTRUCCIÓN DE INFRAESTRUCTURA AGROPECUARIA: CAPTACIÓN Y ALMACENAMIENTO DE AGUA)"]);
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "2001", "programa" => "SERVIDORES PUBLICOS DEL SECTOR CENTRAL"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1006", "programa" => "PROG DE APOYO A LOS FONDOS DE ASEGURAMIENTO AGROPECUARIO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1088", "programa" => "PROG PARA LA CONSTRUCCION Y REHABILITACION DE SISTEMAS DE AGUA POTABLE Y SANEAMIENTO EN ZONAS RURALES"]);
      $programa = Programa::create (["cve_dependencia" => "219000000","id" => "14", "programa" => "COMPROMISO COMUNITARIO"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "141", "programa" => "ESTÍMULOS A INTEGRANTES DE BANDA DE GUERRA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1001", "programa" => "programa DE ABASTO SOCIAL DE LECHE A CARGO DE LICONSA S.A. DE C.V."]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1087", "programa" => "PROG DE AGUA POTABLE, ALCANTARILLADO Y SANEAMIENTO EN ZONAS URBANAS"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1038", "programa" => "PROG DE EDUCACION INICIAL Y BASICA PARA LA POBLACION RURAL E INDIGENA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1119", "programa" => "PROBAPIS"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1037", "programa" => "PROG PARA EL DESARROLLO DE LAS INDUSTRIAS DE ALTA TECNOLOGIA (PRODIAT)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1028", "programa" => "PROG DE FORTALECIMIENTO A LA ORGANIZACION RURAL"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1100", "programa" => "PROG DE OPCIONES PRODUCTIVAS"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1106", "programa" => "programa DE EMPLEO TEMPORAL (PET)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1007", "programa" => "PROG DE ESQUEMA DE FINANCIAMIENTO Y SUBSIDIO FEDERAL PARA VIVIENDA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1039", "programa" => "PROG ATENCION A LA DEMANDA DE EDUCACION PARA ADULTOS (INEA)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1056", "programa" => "PROG NACIONAL DE LECTURA"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "80", "programa" => "REHABILITACIÓN, TECNIFICACIÓN Y EQUIPAMIENTO DE UNIDADES DE RIEGO Y PROYECTOS PRODUCTIVOS EN ZONAS DE ATENCIÓN PRIORITARIA."]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1004", "programa" => "SUBSIDIO A LA PRIMA DEL SEGURO AGROPECUARIO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1120", "programa" => "programa PVR"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1010", "programa" => "PROG FONDOS REGIONALES INDIGENAS (PFRI)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1072", "programa" => "PROG DE ATENCION A FAMILIAS Y POBLACION VULNERABLE"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1031", "programa" => "FONDO NACIONAL DE APOYOS PARA EMPRESAS EN SOLIDARIDAD (FONAES)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "45", "programa" => "BÉCALOS PARA FAMILIAS FUERTES"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "49", "programa" => "MECANIZACION E IMPLEMENTOS AGRICOLAS (TRACTORES)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1117", "programa" => "FORTALECIMIENTO EN LAS ENTIDADES FEDERATIVAS DE LAS CAPACIDADES CIENTIFICAS, TECNOLOGICAS Y DE INNOVACION"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "27", "programa" => "BECAS PARA ESCUELAS PARTICULARES INCORPORADAS A LA SECRETARÍA DE EDUCACIÓN (SUBSISTEMA ESTATAL)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1020", "programa" => "PROG CAPITAL DE RIESGO Y PARA SERVICIOS DE COBERTURA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1102", "programa" => "programa DE AHORRO Y SUBSIDIO PARA LA VIVIENDA TU CASA"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "9", "programa" => "programa DE DESARROLLO SOCIAL GENTE GRANDE VERTIENTE DE 60 A 69 AÑOS DE EDAD"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1012", "programa" => "PROG PROMOCION DE CONVENIOS EN MATERIA DE JUSTICIA (PPCMJ)"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "19", "programa" => "APOYO PARA LA ADQUISICION DE INSUMOS AGRICOLAS (SEMILLAS)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1058", "programa" => "PROG BECA DE APOYO A LA PRACTICA INTENSIVA Y AL SERVICIO SOCIAL PARA ESTUDIANTES DE SEPTIMO Y OCTAVO SEMESTRES DE ESCUELAS NORMALES PUBLICAS"]);
      $programa = Programa::create (["cve_dependencia" => "229000000","id" => "62", "programa" => "INFRAESTRUCTURA PARA ELECTRIFICACION DE VIVIENDAS"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "159", "programa" => "programa DE DESARROLLO SOCIAL SEGURIDAD ALIMENTARIA DEL ESTADO DE MÉXICO-VERTIENTE MENSUAL"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "160", "programa" => "MICROCRÉDITOS EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "161", "programa" => "programa DE BECAS PARA ESTUDIANTES DEL ESTADO DE MEXICO EN: UNAM, IPN Y UAM (PROBEMEX)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "162", "programa" => "DISCAPACIDAD O ENFERMEDAD CRONICO DEGENERATIVA"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "163", "programa" => "ESTIMULO A ESTUDIANTES DE BANDA DE MARCHAS"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "164", "programa" => "ALUMNOS EN ESTADO DE ORFANDAD"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "165", "programa" => "ALUMNOS INMIGRANTES"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "171", "programa" => "FUERZA JOVEN EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "177", "programa" => "programa DE DESARROLLO SOCIAL FOMENTO A LA AGRICULTURA PROTEGIDA"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "178", "programa" => "ALTA PRODUCTIVIDAD"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "179", "programa" => "programa DE DESARROLLO SOCIAL FOMENTO A LA AGRICULTURA ORGÁNICA"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "180", "programa" => "programa DE DESARROLLO SOCIAL programa ESTRATÉGICO DE IMPULSO A LA FLORICULTURA."]);
      $programa = Programa::create (["cve_dependencia" => "226000000","id" => "43", "programa" => "REGISTRO, CREDENCIALIZACIÓN Y ASESORÍA PIROTÉCNICA"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "152", "programa" => "ESCUELAS DE CALIDAD"]);
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "2005", "programa" => "SERVIDORES PUBLICOS DEL SECTOR AUXILIAR"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1118", "programa" => "BECAS ACADEMICAS"]);
      $programa = Programa::create (["cve_dependencia" => "202000000","id" => "44", "programa" => "FIANZAS DE INTERES SOCIAL"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1103", "programa" => "PROG 3 X 1 PARA MIGRANTES"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "116", "programa" => "programa DE DESARROLLO SOCIAL FAMILIAS FUERTES NUTRICIÓN PARA PERSONAS CON DISCAPACIDAD"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "59", "programa" => "INSUMOS AGRÍCOLAS Y MATERIAL VEGETATIVO"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "2", "programa" => "programa DE DESARROLLO INTEGRAL DE ATENCIÓN PRIMARIA A LA SALUD (PRODIAPS- TARJETA FAMILIAR)."]);
      $programa = Programa::create (["cve_dependencia" => "212000000","id" => "90", "programa" => "REFORESTANDO EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "26", "programa" => "FAMILIAS FUERTES SALARIO ROSA"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "84", "programa" => "CONSTRUCCIÓN DE INVERNADEROS EN EL ESTADO DE MÉXICO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1032", "programa" => "FONDO DE APOYO PARA LA MICRO, PEQUEÑA Y MEDIANA EMPRESA (FONDO PYME)"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "20", "programa" => "RACIONES VESPERTINAS"]);
      $programa = Programa::create (["cve_dependencia" => "204000000","id" => "72", "programa" => "EDOMÉX: CAPACITACIÓN PARA EL TRABAJO"]);
      $programa = Programa::create (["cve_dependencia" => "203700000","id" => "777", "programa" => "TEST DESARROLLO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1002", "programa" => "programa 70 Y MAS"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1034", "programa" => "COMITE NACIONAL DE PRODUCTIVIDAD E INNOVACION TECNOLOGICA (COMPITE)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1082", "programa" => "PROARBOL-PROG DE PLANTACIONES FORESTALES COMERCIALES (PRODEPLAN)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1111", "programa" => "RESCATE DE ESPACIOS PUBLICOS"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "85", "programa" => "INFRAESTRUCTURA. EQUIPAMIENTO, MAQUINARIA Y MATERIAL BIOLÓGICO (SUBSECTOR AGRÍCOLA) "]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1044", "programa" => "PROG FONDO DE INVERSION DE UNIVERSIDADES PUBLICAS ESTATALES CON EVALUACION DE LA ANUIES (FIUPEA)"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "204", "programa" => "HEMODIÁLISIS"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "205", "programa" => "BANCO DE TEJIDOS"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "202", "programa" => "MASTOGRAFÍAS"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "203", "programa" => "TRASPLANTES"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "173", "programa" => "FAMILIAS FUERTES CON BECAS ROSAS (BECAS PARA MADRES DE FAMILIA QUE SE ENCUENTRAN ESTUDIANDO)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "188", "programa" => "BECAS EXTRAORDINARIAS PARA EDUCACIÓN MEDIA SUPERIOR"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "206", "programa" => "GRUPO DE AYUDA MUTUA"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "207", "programa" => "BECAS PARA ESTUDIANTES DESTACADOS EN ESCUELAS NORMALES"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "208", "programa" => "FAMILIAS FUERTES, programa PREMIO ESTATAL DE LA JUVENTUD (RECURSO 2017)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "209", "programa" => "BECAS DE CAPACITACIÓN Y DESARROLLO PARA SERVIDORES PÚBLICOS DEL INSTITUTO MEXIQUENSE DE LA INFRAESTRUCTURA FÍSICA EDUCATIVA"]);
      $programa = Programa::create (["cve_dependencia" => "203700000","id" => "888", "programa" => "TEST DESARROLLO 2F"]);
      $programa = Programa::create (["cve_dependencia" => "203700000","id" => "999", "programa" => "TEST DESARROLLO 3F"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "172", "programa" => "BECAS VIAJES AL EXTRANJERO"]);
      $programa = Programa::create (["cve_dependencia" => "204000000","id" => "210", "programa" => "EDOMÉX: CAPACITACIÓN PARA AUTOEMPLEO"]);
      $programa = Programa::create (["cve_dependencia" => "228000000","id" => "175", "programa" => "BECA TALENTO ARTÍSTICO EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "156", "programa" => "EQUIPO TIFLOTÉCNICO A MAESTROS"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "123", "programa" => "DESARROLLO RURAL INTEGRAL PARA FAMILIAS FUERTES (CANASTA ROSA ALIMENTARIA HORTOFRUTÍCOLA)"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "100", "programa" => "programa DE DESARROLLO SOCIAL FAMILIAS FUERTES PARA COMUNIDADES PRODUCTIVAS"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "54", "programa" => "COMPROMISO SEGURIDAD ALIMENTARIA DEL ESTADO DE MEXICO VERTIENTE ZONAS DE ATENCION PRIORITARIA (ZAP)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1011", "programa" => "PROG ORGANIZACION PRODUCTIVA PARA MUJERES INDIGENAS (POPMI)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "157", "programa" => "COMPUTADORAS TIFLOTECNICAS PARA CAM Y ESCUELAS FORMADORAS"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "6", "programa" => "FAMILIAS FUERTES APOYO A PERSONAS ADULTAS MAYORES"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1016", "programa" => "FONDO DE CONTINGENCIAS Y AUTOSEGURO"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "213", "programa" => "REPOBLACION OVINA MEXIQUENSE"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "212", "programa" => "DESARROLLO RURAL INTEGRAL PARA FAMILIAS FUERTES (PAQUETE CÁRNICO ROSA)"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "216", "programa" => "programa DE DESARROLLO SOCIAL OTORGAMIENTO DE BECAS A NIÑAS, NIÑOS Y ADOLESCENTES REPATRIADOS Y EN RIESGO DE MIGRACIÓN"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "217", "programa" => "CÁNCER TESTICULAR"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "218", "programa" => "CÁNCER DE PRÓSTATA"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "214", "programa" => "BECAS PARA TALENTOS ARTÍSTICOS"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "215", "programa" => "BECAS PARA TALENTOS DEPORTIVOS"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "225", "programa" => "programa DE DESARROLLO SOCIAL FAMILIAS FUERTES VISIÓN PARA EL FUTURO (ADULTOS MAYORES)"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "258", "programa" => "FAMILIAS FUERTES PROMOCIÓN DE LOS PROGRAMAS DEL INSTITUTO MEXIQUENSE DEL EMPRENDEDOR"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "259", "programa" => "RED EMPRENDEDORES EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "260", "programa" => "FAMILIAS FUERTES FERIA REGIONAL DE PROMOCIÓN DEL CRÉDITO A EMPRENDEDORES Y MIPYMES, MEXIQUENSE 2018"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "261", "programa" => "PROMOVER LA ATRACCIÓN DE LA INVERSIÓN PRODUCTIVA QUE PERMITA LA CREACIÓN DE PARQUES CIENTÍFICOS Y TECNOLÓGICOS EN EL ESTADO DE MÉXICO"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "262", "programa" => "ATENDER SOLICITUDES DE INDUSTRIALES ESTABLECIDOS EN EL ESTADO DE MÉXICO E INTERESADOS EN INVERTIR"]);
      $programa = Programa::create (["cve_dependencia" => "212000000","id" => "263", "programa" => "EDOMÉX PROCARBONO"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "289", "programa" => "SALARIO ROSA POR LA EDUCACIÓN"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "274", "programa" => "ACCIÓN DE DESARROLLO SOCIAL FAMILIAS FUERTES DESARROLLO INTEGRAL INDÍGENA "]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "275", "programa" => "ACCIÓN DE DESARROLLO SOCIAL TU ESTUFA CON TODO"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "276", "programa" => "ORGULLO ORIGINARIO EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "277", "programa" => "MEXIQUENSES POR UNA VIDA SIN VIOLENCIA"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "278", "programa" => "ACCIÓN DE DESARROLLO SOCIAL ESTRATEGIA FAMILIAS FUERTES COMUNIDADES CON TODO"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "290", "programa" => "SALARIO ROSA BECA EDUCATIVA"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "291", "programa" => "POR VULNERAVILIDAD O CONTINGENCIA"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "292", "programa" => "PROYECTOS PRODUCTIVOS"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "293", "programa" => "COMUNIDAD FUERTE EDOMEX"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "294", "programa" => "FAMILIAS FUERTES DESARROLLO INTEGRAL INDIGENA"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "295", "programa" => "BIENES SOCIALES"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "296", "programa" => "DESARROLLO PECUARIO"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "297", "programa" => "PROYECTOS ESPECIALES PECUARIOS"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "298", "programa" => "PROYECTO DE IMPULSO A LA GANADERÍA"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "299", "programa" => "FIGAMEX (ENGORDA DE GANADO) "]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "300", "programa" => "ACCIONES PRIORITARIAS ZOOSANITARIAS Y ACUICOLAS"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "301", "programa" => "ASOCIATIVIDAD PRODUCTIVA RURAL"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "302", "programa" => "PROYECTOS PRODUCTIVOS"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "303", "programa" => "SALARIO ROSA PARA EL CAMPO"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "304", "programa" => "PROYECTOS AGROINDUSTRIALES"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "305", "programa" => "FORTALECIMIENTO AL PROYECTO ESTRATEGICO MEZCAL"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "306", "programa" => "USO EFICIENTE DEL AGUA"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "307", "programa" => "INVESTIGACIÓN, TRANSFERENCIA  DE TECNOLOGÍA Y PRODUCCIÓN DE SEMILLA"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "308", "programa" => "CAPACITACIÓN Y CONSULTORÍA PARA EL DESARROLLO AGROEMPRESARIAL"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "320", "programa" => "SUPERVISIÓN, EVALUACIÓN Y TRANSPARENCIA DE LA INFORMACIÓN"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "219", "programa" => "programa DE BECAS PARA ALUMNOS CON AUTISMO"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "271", "programa" => "SALUD BUCAL MEXIQUENSE"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "272", "programa" => "DE PASEO CON ADULTOS MAYORES EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "273", "programa" => "CASA DE DÍA EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "321", "programa" => "APOYO A LA INFRAESTRUCTURA HIDROAGRÍCOLA"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "322", "programa" => "programa EN CONCURRENCIA CON ENTIDADES FEDERATIVAS"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "323", "programa" => "programa DESARROLLO RURAL"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "324", "programa" => "programa DE SISTEMA NACIONAL DE INFORMACIÓN PARA EL DESARROLLO RURAL SUSTENTABLE"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "325", "programa" => "programa DE SANIDAD E INOCUIDAD AGROALIMENTARIA"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "309", "programa" => "FERIAS DE EMPRENDIMIENTO EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "208000000","id" => "310", "programa" => "SALARIO ROSA POR EL EMPRENDIMIENTO"]);
      $programa = Programa::create (["cve_dependencia" => "225000000","id" => "311", "programa" => "DESARROLLO DE ESPACIOS ARTESANALES EN DESTINOS CON POTENCIAL TURISTICO"]);
      $programa = Programa::create (["cve_dependencia" => "225000000","id" => "312", "programa" => "FORTALECIMIENTO A TALLERES ARTESANALES"]);
      $programa = Programa::create (["cve_dependencia" => "225000000","id" => "313", "programa" => "ENTREGA DE MATERIA PRIMA"]);
      $programa = Programa::create (["cve_dependencia" => "228000000","id" => "314", "programa" => "SALARIO ROSA POR LA CULTURA COMUNITARIA"]);
      $programa = Programa::create (["cve_dependencia" => "212000000","id" => "315", "programa" => "PLANTACIONES FORESTALES COMERCIALES"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "316", "programa" => "FAMILIAS FUERTES, NUTRICIÓN EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "317", "programa" => "APOYOS PRODUCTIVOS COMUNITARIOS EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "318", "programa" => "SALARIO ROSA POR EL DESARROLLO INTEGRAL DE LA FAMILIA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1114", "programa" => "BECAS DE POSGRADO Y OTRAS MODALIDADES DE APOYO A LA CALIDAD"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "136", "programa" => "COMPUTADORAS PARA ESTUDIANTES CON MEJORES PROMEDIOS EN EDUCACIÓN SECUNDARIA, MEDIA SUPERIOR Y SUPERIOR"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "5002", "programa" => "DIRECCION GENERAL DE EDUCACION SUPERIOR"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1066", "programa" => "PROG DE ESCUELA SEGURA"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "124", "programa" => "programa DE DESARROLLO SOCIAL SEGURIDAD ALIMENTARIA VERTIENTE ESTRATÉGICA POR NECESIDADES NUTRICIONALES"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1078", "programa" => "PROG DE LA MUJER EN EL SECTOR AGRARIO (PROMUSAG)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "146", "programa" => "COMPUTADORAS PARA CAM"]);
      $programa = Programa::create (["cve_dependencia" => "212000000","id" => "104", "programa" => "PAGO POR SERVICIOS AMBIENTALES HIDROLÓGICOS DEL ESTADO DE MÉXICO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1067", "programa" => "HABILIDADES DIGITALES PARA TODOS"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "15", "programa" => "TARJETA COMPROMISO DE DESCUENTOS PARA ADULTOS MAYORES"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "111", "programa" => "SERVICIO SOCIAL COMUNITARIO PARA FAMILIAS FUERTES (programa DE DESARROLLO SOCIAL SERVICIO SOCIAL COMUNITARIO)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1049", "programa" => "MODELO DE EDUCACION PARA LA VIDA Y EL TRABAJO (INEA)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1053", "programa" => "PROG ASESOR TECNICO PEDAGOGICO"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "60", "programa" => "EDUCACIÓN A DISTANCIA (PREPANET)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "12", "programa" => "SEGURO ESTUDIANTIL EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "5", "programa" => "NIVEL SUPERIOR"]);
      $programa = Programa::create (["cve_dependencia" => "224000000","id" => "48", "programa" => "FONDOS PARA VIVIENDA PROGRESIVA"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "75", "programa" => "PROYECTOS DE DESARROLLO INDÍGENA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1071", "programa" => "PROG PARA LA PROTECCION Y DESARROLLO INTEGRAL DE LA INFANCIA"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "135", "programa" => "COMPUTADORAS PARA ESCUELAS CON LABORATORIOS"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "55", "programa" => "FAMILIAS FUERTES, NUTRICIÓN EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1108", "programa" => "PROG DE APOYO ALIMENTARIO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1068", "programa" => "PROG COMUNIDADES SALUDABLES"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "50", "programa" => "COMPROMISO SEGURIDAD ALIMENTARIA DEL ESTADO DE MEXICO VERTIENTE FAO (ZONA TOLUCA)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "9998", "programa" => "DUMMY"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "2004", "programa" => "MAGISTERIO DEL SUBSISTEMA FEDERALIZADO"]);
      $programa = Programa::create (["cve_dependencia" => "226000000","id" => "64", "programa" => "VIVIENDA DIGNA PARA AGENTES DE SEGURIDAD Y POLICÍA MINISTERIAL  (VIDA)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1077", "programa" => "PROG DE APOYO AL EMPLEO (PAE)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1115", "programa" => "SISTEMA NACIONAL DE INVESTIGADORES"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1055", "programa" => "PROG DEL SISTEMA NACIONAL DE FORMACION CONTINUA Y SUPERACION PROFESIONAL DE MAESTROS DE EDUCACION BASICA EN SERVICIO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1018", "programa" => "PROG INTEGRAL DE FORMACION, CAPACITACION Y CONSULTORIA PARA PRODUCTORES INTERMEDIARIOS FINANCIEROS RURALES"]);
      $programa = Programa::create (["cve_dependencia" => "225000000","id" => "92", "programa" => "FOMENTO ARTESANAL MEXIQUENSE"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "118", "programa" => "programa DE DESARROLLO SOCIAL ENTREGA DE BECAS METRUM"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1079", "programa" => "FONDO DE APOYO PARA PROYECTOS PRODUCTIVOS (FAPPA)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1080", "programa" => "JOVEN EMPRENDEDOR RURAL Y FONDO DE TIERRAS"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "150", "programa" => "EQUIPO DE MEDICIÓN DE LA CAPACIDAD FUNCIONAL"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "25", "programa" => "APOYO PARA TRANSPORTE EN ZONAS OBRERO-POPULARES"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1036", "programa" => "COMPETITIVIDAD EN LOGISTICA Y CENTRALES DE ABASTO"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "87", "programa" => "INFRAESTRUCTURA. EQUIPAMIENTO, MAQUINARIA Y MATERIAL BIOLÓGICO (SUBSECTOR PECUARIO) "]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1110", "programa" => "programa DE ESTANCIAS INFANTILES PARA APOYAR A MADRES TRABAJADORAS"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "151", "programa" => "BECAS DE DESARROLLO SOCIAL PERMANENCIA ESCOLAR"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "83", "programa" => "INFRAESTRUCTURA, TECNIFICACIÓN Y EQUIPAMIENTO"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "5000", "programa" => "PORTAL ESTUDIANTIL"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1030", "programa" => "FONDO DE MICROFINANCIAMIENTO A MUJERES RURALES (FOMMUR)"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "13", "programa" => "FAMILIAS FUERTES NIÑEZ INDÍGENA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1065", "programa" => "PROG ESCUELAS DE TIEMPO COMPLETO"]);
      $programa = Programa::create (["cve_dependencia" => "224000000","id" => "29", "programa" => "PISO FIRME"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "120", "programa" => "DESARROLLO RURAL INTEGRAL PARA FAMILIAS FUERTES (APOYOS ECONÓMICOS A LOS PRODUCTORES PARA EL DESARROLLO DE PROYECTOS PRODUCTIVOS: APOYOS QUE MEJOREN LA VIVIENDA RURAL)"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "128", "programa" => "JÓVENES EMPRENDEDORES"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "319", "programa" => "SALARIO ROSA POR LA VULNERABILIDAD"]);
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "287", "programa" => "APOYO PARA JÓVENES INVESTIGADORES EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "204000000","id" => "288", "programa" => "SALARIO ROSA PARA EL  TRABAJO"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "326", "programa" => "MAQUINARIA PARA LA CONSTRUCCIÓN DE INFRAESTRUCTURA RURAL"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "327", "programa" => "INFRAESTRUCTURA PARA EL DESARROLLO AGROPECUARIO"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "328", "programa" => "PREVENCIÓN Y ATENCIÓN A DESASTRES NATURALES"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "329", "programa" => "SEGURO AGRÍCOLA CATASTRÓFICO"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "332", "programa" => "FONDOS DE ASEGURAMIENTO"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "334", "programa" => "PROYECTOS PARA PEQUEÑOS Y MEDIANOS PRODUCTORES Y/O PRODUCTORAS"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "335", "programa" => "RIEGO POR GRAVEDAD TECNIFICADO (RIGRAT) EN UNIDADES DE RIEGO"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "350", "programa" => "PROYECTOS ESTRATEGICOS"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "351", "programa" => "SANITIZACIÓN AGROPECUARIA"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "352", "programa" => "TERRITORIOS MAS FUERTES"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "353", "programa" => "REEMBOLSO DE INTERESES"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "354", "programa" => "CAPACITACION Y ASISTENCIA TECNICA"]);
      $programa = Programa::create (["cve_dependencia" => "224000000","id" => "47", "programa" => "FONDOS PARA EL MEJORAMIENTO DE LA VIVIENDA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1099", "programa" => "PROG DE ABASTO RURAL A CARGO DE DICONSA, SA DE CV (DICONSA)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "108", "programa" => "BECAS PRIMARIA"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "112", "programa" => "COMPROMISO CON LA DISCAPACIDAD"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "148", "programa" => "ESTÍMULO A INTEGRANTES DE ASOCIACIONES DE PADRES DE FAMILIA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1064", "programa" => "PROG DE APOYO A LA INFRAESTRUCTURA CULTURAL DE LOS ESTADOS (PAICE)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1073", "programa" => "RESPONSABLES DEL programa DE ESTANCIAS INFANTILES PARA APOYAR A MADRES TRABAJADORAS"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "133", "programa" => "SILLAS PARA ESTUDIANTES ZURDOS"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "46", "programa" => "APOYOS ASISTENCIALES A MENORES PARA MEJORAR SU CALIDAD DE VIDA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1060", "programa" => "DEPORTE"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1094", "programa" => "PROG DE MODERNIZACION Y TECNIFICACION DE UNIDADES DE RIEGO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1043", "programa" => "PROG FONDO DE MODERNIZACION PARA LA EDUCACION SUPERIOR (FOMES)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1096", "programa" => "PROARBOL- APOYO PARA LAS ACCIONES PREVENTIVAS DE INCENDIOS FORESTALES"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1104", "programa" => "programa DE ATENCION A JORNALEROS AGRICOLAS"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "63", "programa" => "programa NORMAL DE APOYO EN ESPECIE A PERSONAS FÍSICAS"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1085", "programa" => "PROG DE DESARROLLO INSTITUCIONAL AMBIENTAL (PDIA)"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "8", "programa" => "programa DE DESARROLLO SOCIAL FAMILIAS FUERTES POR UN MEJOR FUTURO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1022", "programa" => "PROG PARA LA ADQUISICION DE ACTIVOS PRODUCTIVOS"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1052", "programa" => "PROG DE EDUCACION BASICA PARA NIÑOS Y NIÑAS DE FAMILIAS JORNALERAS AGRICOLAS MIGRANTES"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1091", "programa" => "PROARBOL-PROG DE PAGO POR SERVICIOS AMBIENTALES (PSA)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1101", "programa" => "PROG DEL FONDO NACIONAL DE FOMENTO A LAS ARTESANIAS (FONART)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "40", "programa" => "SEGURO ESTUDIANTIL EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "223000000","id" => "93", "programa" => "OTORGAMIENTO DE CONCESIONES, PERMISOS Y AUTORIZACIONES  PARA LA PRESTACIÓN DEL SERVICIO DE  TRANSPORTE PÚBLICO"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "101", "programa" => "FAMILIAS FUERTES, NUTRICIÓN EDOMÉX, ATENCIÓN A MENORES DE 5 AÑOS NO ESCOLARIZADOS"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1093", "programa" => "PROARBOL-PROG DE SERVICIOS AMBIENTALES POR CAPTURA DE CARBONO, BIODIVERSIDAD Y SISTEMAS AGROFORESTALES (CABSA)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1116", "programa" => "FORTALECIMIENTO A NIVEL SECTORIAL DE LAS CAPACIDADES CIENTIFICAS, TECNOLOGICAS Y DE INNOVACION"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "107", "programa" => "BECAS PARA PERSONAS CON DISCAPACIDAD PERMANENTE INTEGRADAS A EDUCACION REGULAR"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "52", "programa" => "MUJERES TRABAJADORAS COMPROMETIDAS (SEDAGRO)"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "56", "programa" => "FAMILIAS FUERTES, APOYOS FUNCIONALES PARA PERSONAS CON DISCAPACIDAD"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1074", "programa" => "CARAVANAS DE LA SALUD"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "134", "programa" => "ESTÍMULOS PARA ESTUDIANTES CIEGOS (SEDUC)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "147", "programa" => "PAQUETES PARA REHABILITACIÓN DE PLANTELES"]);
      $programa = Programa::create (["cve_dependencia" => "223000000","id" => "113", "programa" => "CONDUCE SEGURO EDOMÉX. LICENCIA DE SERVICIO PÚBLICO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1095", "programa" => "FONDO CONCURSABLE PARA EL TRATAMIENTO DE AGUAS RESIDUALES"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "88", "programa" => "APOYOS ECONÓMICOS A LOS PRODUCTORES PARA EL DESARROLLO DE LOCALIDADES RURALES"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "70", "programa" => "ATENCION A LA SALUD DEL ADULTO Y EL ANCIANO"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "117", "programa" => "programa DE DESARROLLO SOCIAL FAMILIAS FUERTES CON APOYO HORTA-DIF"]);
      $programa = Programa::create (["cve_dependencia" => "212000000","id" => "96", "programa" => "MI ESTUFA ECOLÓGICA EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1033", "programa" => "PROG NACIONAL DE FINANCIAMIENTO AL MICROEMPRESARIO"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "81", "programa" => "EQUIPAMIENTO Y REHABILITACIÓN DE EQUIPOS DE POZOS Y PLANTAS DE BOMBEO"]);
      $programa = Programa::create (["cve_dependencia" => "204000000","id" => "17", "programa" => "BECA EDOMÉX PARA HIJOS DE TRABAJADORES SINDICALIZADOS"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1061", "programa" => "SISTEMA MEXICANO DEL DEPORTE DE ALTO RENDIMIENTO"]);
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "69", "programa" => "programa DE BECAS DEL CONSEJO MEXIQUENSE DE CIENCIA Y TECNOLOGÍA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1075", "programa" => "SEGURO MEDICO PARA UNA NUEVA GENERACION"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "74", "programa" => "COMPROMISO PARA EL DESARROLLO DE LAS COMUNIDADES DEL ESTADO DE MÉXICO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1059", "programa" => "CULTURA FISICA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1027", "programa" => "PROG DE ATENCION A PROBLEMAS ESTRUCTURALES"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1040", "programa" => "PROG DE MEJORAMIENTO DEL PROFESORADO (PROMEP)"]);
      $programa = Programa::create (["cve_dependencia" => "224000000","id" => "18", "programa" => "FAMILIAS FUERTES EN SU PATRIMONIO "]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "97", "programa" => "programa DE DESARROLLO SOCIAL FAMILIAS FUERTES APOYOS COMUNITARIOS"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "158", "programa" => "ESTIMULO PARA ESTUDIANTES CIEGOS SEDESEM"]);
      $programa = Programa::create (["cve_dependencia" => "204000000","id" => "3", "programa" => "APOYOS DE CAPACITACIÓN PARA EMPLEABILIDAD"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "105", "programa" => "BECAS 2010"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "142", "programa" => "EQUIPAMIENTO DE BANDAS DE GUERRA"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "145", "programa" => "BECA ANUAL PARA ESTUDIANTE CIEGO"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "73", "programa" => "BECAS PARA INTERNADOS"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "79", "programa" => "DESARROLLO DE LA INFRAESTRUCTURA AGROPECUARIA FAMILIAS FUERTES (USO EFICIENTE DEL AGUA REVESTIMIENTO Y ENTUBADO DE CANALES)"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "122", "programa" => "AVICULTURA FAMILIAR"]);
      $programa = Programa::create (["cve_dependencia" => "204000000","id" => "16", "programa" => "ESTRATEGIA EMPLEO FORMAL"]);
      $programa = Programa::create (["cve_dependencia" => "224000000","id" => "65", "programa" => "VIVIENDA DIGNA"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "103", "programa" => "EDOMÉX DE LA MANO CONTIGO"]);
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "2002", "programa" => "MAGISTERIO DEL SUBSISTEMA ESTATAL"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1026", "programa" => "PROG DE INDUCCION Y DESARROLLO DEL FINANCIAMIENTO AL MEDIO RURAL"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "22", "programa" => "SEGURO POPULAR + PRODIAPS"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "57", "programa" => "BECAS DE ESCUELAS PARTICULARES INCORPORADAS A SEIEM"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "78", "programa" => "REHABILITACION, TECNIFICACION Y EQUIPAMIENTO DE DISTRITOS  DE RIEGO"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "129", "programa" => "RAMO 20"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1013", "programa" => "PROG DE FOMENTO Y DESARROLLO DE LAS CULTURAS INDIGENAS (PFDCI)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1076", "programa" => "SISTEMA INTEGRAL DE CALIDAD EN SALUD"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1107", "programa" => "PROG DE VIVIENDA RURAL"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "144", "programa" => "EQUIPO TIFLOTÉCNICO PERSONAL PARA MAESTROS Y ESTUDIANTES CIEGOS"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1024", "programa" => "PROG DE USO SUSTENTABLE DE RECURSOS NATURALES PARA LA PRODUCCION PRIMARIA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1089", "programa" => "PROG DE REHABILITACION Y MODERNIZACION DE DISTRITOS DE RIEGO"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "149", "programa" => "PAQUETE DEPORTIVO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1050", "programa" => "MODELO COMUNITARIO DE EDUCACION INICIAL Y BASICA PARA POBLACION INDIGENA Y MIGRANTE (CONAFE)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "132", "programa" => "DESAYUNADORES ESCOLARES (REHABILITACIÓN DE ESPACIOS PARA CONSUMO DE ALIMENTOS)"]);
      $programa = Programa::create (["cve_dependencia" => "224000000","id" => "66", "programa" => "EDIFICACIÓN DE CASA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1017", "programa" => "PROG DE GARANTIAS LIQUIDAS"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1113", "programa" => "PROG PARA EL DESARROLLO DE ZONAS PRIORITARIAS"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "102", "programa" => "ACCIÓN DE DESARROLLO SOCIAL OFTALMOLOGÍA COMUNITARIA (CIRUGÍA DE CATARATAS Y ESTRABISMO)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1057", "programa" => "PROG PARA EL FORTALECIMIENTO DEL SERVICIO DE LA EDUCACION TELESECUNDARIA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1069", "programa" => "PROG DE ATENCION A PERSONAS CON DISCAPACIDAD"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "119", "programa" => "APOYO A LA ADQUISICIÓN DE DIESEL PARA LA PRODUCCIÓN AGRÍCOLA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1051", "programa" => "programa BECAS DE APOYO A LA EDUCACION BASICA DE MADRES JOVENES Y JOVENES EMBARAZADAS"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "143", "programa" => "ESTIMULO A DESAYUNADORES ESCOLARES PARA ADQUISICIÓN DE ENSERES"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "168", "programa" => "programa DE DESARROLLO SOCIAL DE LA MANO CON PAPA"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "211", "programa" => "MUJERES POR UN FUTURO CONSTRUCTIVO"]);
      $programa = Programa::create (["cve_dependencia" => "227000000","id" => "190", "programa" => "OFICIALÍA MÓVIL EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "227000000","id" => "191", "programa" => "ADULTOS MAYORES EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "227000000","id" => "192", "programa" => "FIANZAS DE INTERÉS SOCIAL"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "23", "programa" => "APOYO PARA LA ADQUISICION DE INSUMOS AGRICOLAS (FERTILIZANTES)"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "61", "programa" => "programa CIRUGÍA EXTRAMUROS DEL INSTITUTO DE SALUD DEL ESTADO DE MÉXICO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1063", "programa" => "PROG DE APOYO A COMUNIDADES PARA RESTAURACION DE MONUMENTOS Y BIENES ARTISTICOS DE PROPIEDAD FEDERAL (FOREMOBA)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "110", "programa" => "BECAS PREPARATORIA"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "99", "programa" => "RACIONES FRÍAS"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "71", "programa" => "TRATAMIENTOS SUBROGADOS EN ADICCIONES"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1025", "programa" => "PROG DE SOPORTE"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1092", "programa" => "PROARBOL programa DE CONSERVACION Y RESTAURACION DE ECOSISTEMAS FORESTALES (PROCOREF)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "131", "programa" => "ESTIMULO A ESCOLTAS DE BANDERA"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "53", "programa" => "CARENCIA ALIMENTARIA"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "125", "programa" => "programa DE DESARROLLO SOCIAL SEGURIDAD ALIMENTARIA VERTIENTE ESTRATÉGICA POR VULNERABILIDAD"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1048", "programa" => "PROG DE ACCIONES COMPENSATORIAS PARA ABATIR EL REZAGO EDUCATIVO EN EDUCACION INICIAL Y BASICA (CONAFE)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "140", "programa" => "SEGURO CONTRA ACCIDENTES PARA LOS NIVELES PREESCOLAR Y SECUNDARIA."]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "2003", "programa" => "TECNICAS DE ATENCION PRIMARIA A LA SALUD Y CUIDADORAS DE LA SALUD"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1083", "programa" => "programa DE CONSERVACION PARA EL DESARROLLO SOSTENIBLE (PROCODES)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1081", "programa" => "PROARBOL-PROG DE DESARROLLO FORESTAL (PRODEFOR)"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "114", "programa" => "programa DE DESARROLLO SOCIAL OTORGAMIENTO DE ZAPATO ORTOPÉDICO"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1021", "programa" => "PROCAMPO PARA VIVIR MEJOR"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "130", "programa" => "programa DE INFRAESTRUCTURA BÁSICA PARA LA ATENCIÓN DE LOS PUEBLOS INDÍGENAS (PIBAI)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1014", "programa" => "PROG TURISMO ALTERNATIVO EN ZONAS INDIGENAS (PTAZI)"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "115", "programa" => "programa DE DESARROLLO SOCIAL FAMILIAS FUERTES VISIÓN PARA EL FUTURO (NIÑO)"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "109", "programa" => "BECAS SECUNDARIA"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1045", "programa" => "PROG DE FORTALECIMIENTO DE LA EDUCACION ESPECIAL Y DE LA INTEGRACION EDUCATIVA"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "58", "programa" => "BECAS ECONOMICAS"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "139", "programa" => "FAMILIAS FUERTES CON ÚTILES ESCOLARES"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "126", "programa" => "programa DE DESARROLLO SOCIAL FAMILIAS FUERTES CRECIENDO CONTIGO"]);
      $programa = Programa::create (["cve_dependencia" => "215000000","id" => "127", "programa" => "programa DE DESARROLLO SOCIAL FAMILIAS FUERTES FORTALECIENDO COMUNIDADES"]);
      $programa = Programa::create (["cve_dependencia" => "201B00000","id" => "98", "programa" => "RACIONES CALIENTES"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1003", "programa" => "programa DE DESARROLLO HUMANO OPORTUNIDADES"]);
      $programa = Programa::create (["cve_dependencia" => "217000000","id" => "1", "programa" => "SISTEMA DE PROTECCIÓN SOCIAL EN SALUD (SEGURO POPULAR)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1009", "programa" => "PROG DE INFRAESTRUCTURA BASICA PARA LA ATENCION DE LOS PUEBLOS INDIGENAS (PIBAI)"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "121", "programa" => "MICROTÚNELES PARA FAMILIAS RURALES"]);
      $programa = Programa::create (["cve_dependencia" => "201000000","id" => "9999", "programa" => "DUMMY (CLAVES INCORRECTAS DEL FUR IMPRESO)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1097", "programa" => "PROG IMSS-OPORTUNIDADES"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1062", "programa" => "programa DE APOYO A LAS CULTURAS MUNICIPALES Y COMUNITARIAS (PACMYC)"]);
      $programa = Programa::create (["cve_dependencia" => "202000000","id" => "28", "programa" => "VIGILANTES VOLUNTARIOS (VI-VO)"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1046", "programa" => "PROG DE MEJORAMIENTO INSTITUCIONAL DE LAS ESCUELAS NORMALES PUBLICAS"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1054", "programa" => "PROG EDUCATIVO RURAL"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "86", "programa" => "INFRAESTRUCTURA. EQUIPAMIENTO, MAQUINARIA Y MATERIAL BIOLÓGICO (SUBSECTOR PESCA Y ACUÍCOLA) "]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1105", "programa" => "PROG DE COINVERSION SOCIAL"]);
      $programa = Programa::create (["cve_dependencia" => "223000000","id" => "95", "programa" => "SUBSIDIOS EN EL PAGO DE DERECHOS POR SERVICIOS PRESTADOS POR LA SECRETARÍA DE TRANSPORTE"]);
      $programa = Programa::create (["cve_dependencia" => "205000000","id" => "5001", "programa" => "DIRECCION GENERAL DE EDUCACION MEDIA SUPERIOR"]);
      $programa = Programa::create (["cve_dependencia" => "999999999","id" => "1112", "programa" => "programa DE APOYO A LOS AVECINDADOS EN CONDICIONES DE POBREZA PATRIMONIAL PARA REGULARIZAR ASENTAMIENTOS HUMANOS IRREGULARES (PASPRAH)"]);
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "264", "programa" => "BECA DE POSGRADO EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "265", "programa" => "BECA DE TITULACIÓN EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "266", "programa" => "BECA TALENTO EDOMÉX EN EL EXTRANJERO"]);
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "267", "programa" => "BECA DE EDUCACIÓN DUAL EDOMÉX"]);
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "268", "programa" => "APOYO A ESTUDIANTES, PROFESORES E INVESTIGADORES DESTACADOS EN CIENCIA Y TECNOLOGIA COMECYT-EDOMEX"]);
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "269", "programa" => "programa JÓVENES EN LA INVESTIGACIÓN Y DESARROLLO TECNOLÓGICO"]);
      $programa = Programa::create (["cve_dependencia" => "203000000","id" => "270", "programa" => "programa PARA LA REALIZACIÓN DE ESTANCIAS DE INVESTIGACIÓN CIENTÍFICA Y/O TECNOLÓGICA"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "330", "programa" => "ALTA PRODUCTIVIDAD"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "331", "programa" => "ATENCIÓN A PRIORIDADES"]);
      $programa = Programa::create (["cve_dependencia" => "207000000","id" => "333", "programa" => "ASEGURAMIENTO DE HUERTAS DE AGUACATE"]);

    }
}
